- hosts: localhost
  vars:
    current_user: "{{ ansible_user_id }}"
  tasks:
    - name: Get home directory
      set_fact:
        home_dir: "{{ lookup('env', 'HOME') }}"
      tags: always
    
    - name: Update
      apt:

    - name: Set theme
      shell: |
        gsettings set org.gnome.desktop.interface gtk-theme 'Yaru-purple-dark'
        gsettings set org.gnome.desktop.interface icon-theme 'Yaru-purple'
      tags: [ gnome, theme ]

    - name: Set some sensible personal defaults
      shell: |
        gsettings set org.gnome.shell.extensions.ding show-home false
        gsettings set org.gnome.desktop.notifications show-banners false
        gsettings set org.gnome.desktop.notifications show-in-lock-screen false
        gsettings set org.gnome.desktop.peripherals.mouse accel-profile 'flat'
        gsettings set org.gnome.desktop.peripherals.touchpad speed 0.3
        gsettings set org.gnome.desktop.peripherals.mouse speed 0
        gsettings set org.gnome.desktop.interface enable-animations false
      tags: [ gnome, gnome-defaults ]

    - name: Disable extensions
      shell: |
        gnome-extensions disable drive-menu@gnome-shell-extensions.gcampax.github.com
        gnome-extensions disable ubuntu-dock@ubuntu.com
      tags: [ gnome, disable-extensions ]

    - name: Set workspace options
      shell: | 
        gsettings set org.gnome.mutter dynamic-workspaces false
        gsettings set org.gnome.desktop.wm.preferences num-workspaces 4
      tags: [ gnome, workspace-options ]

    # Mapping files /usr/share/gnome-control-center/keybindings/
    - name: Set workspace keybinds
      shell: |
        gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-1 "['<Super>d']"
        gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-2 "['<Super>f']"
        gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-3 "['<Super>c']"
        gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-4 "['<Super>v']"
        gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-1 "['<Super><Alt>d']"
        gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-2 "['<Super><Alt>f']"
        gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-3 "['<Super><Alt>c']"
        gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-4 "['<Super><Alt>v']"
      tags: [ gnome, binds ]

    - name: Diable auto color change
      shell: systemctl --user mask --now org.gnome.SettingsDaemon.Color.service
      tags: [ gnome, color-service]

    - name: Install JetBrains Mono font
      become: true
      apt: name=fonts-jetbrains-mono
      tags: [ font ]

    - name: Install git
      become: true
      apt: name=git
      tags: [ utils ]

    - name: Clone fzf
      git:
        repo: https://github.com/junegunn/fzf.git
        dest: "{{ home_dir }}/.fzf"
        depth: 1
      tags: [ fzf, utils ]

    - name: Install fzf
      expect:
        command: "{{ home_dir }}/.fzf/install" 
        responses:
          Do you want:
            - y
            - y
            - y
      tags: [ fzf, utils ]

    - name: Install Utils
      become: true
      apt:
        pkg:
          - zsh
          - tmux
      tags: [ utils ]

    - name: Change shell
      become: true
      user:
        name: "{{ current_user }}"
        shell: /usr/bin/zsh

    - name: Install oh-my zsh
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      tags: [ oh-my-zsh, utils ]

    - name: Install neovim
      become: true
      snap:
        name: nvim
        classic: true
      tags: [ nvim ]

    - name: neovim plugin dependencies
      apt:
        pkg:
          - python3-venv
          - ripgrep
          - gcc
          - clang
      tags: [ nvim ]

    - name: Install nvm
      shell: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
      args:
        creates: "{{ home_dir }}/.nvm/nvm.sh"
      tags: [ nvim, node ]

    - name: Install node
      shell: |
        nvm install node
      tags: [ nvim, node ]
    - name: Install zsh-nvm
      git:
        repo: https://github.com/lukechilds/zsh-nvm
        dest: "{{ home_dir }}/.oh-my-zsh/custom/plugins/zsh-nvm"
      tags: [ node ]

    - name: Install fdfind for fzf
      become: true
      apt: name=fd-find
      tags: [ fdfind ]

    - name: Install make
      become: true
      apt: name=make
      tags: [ make, popshell ]

    - name: Alacritty ppa
      become: true
      apt_repository:
        repo: ppa:mmstick76/alacritty

    - name: Install Alacritty
      become: true
      apt:
        name: alacritty
      update_cache: yes
      tags: [ alacritty ]

    - name: Set alacritty as default terminal
      shell: | 
        gsettings set org.gnome.desktop.default-applications.terminal exec 'alacritty'
        gsettings set org.gnome.desktop.default-applications.terminal exec-arg ''
      tags: [ alacritty ]

    - name: Install typescript
      become: true
      apt: name=node-typescript
      tags: [ make, typescript, popshell ]

    - name: Clone pop shell
      git:
        repo: https://github.com/pop-os/shell.git
        dest: "{{ home_dir }}/.shell"
        version: master_noble
      tags: [ popshell ]

    - name: Build pop shell
      expect:
        chdir: "{{ home_dir }}/.shell"
        command: make local-install
        responses:
          Pop: "y"
      tags: [ popshell ]
