[general]
live_config_reload = true
import = ["~/.config/alacritty/kanagawa.toml"]

[window]
padding.x = 10
padding.y = 10
opacity = 0.85
startup_mode = "Maximized"

[font]
normal.family = "JetBrainsMono Nerd Font Mono"
normal.style = "Regular"
bold.family = "JetBrainsMono Nerd Font Mono"
italic.family = "JetBrainsMono Nerd Font Mono"
bold_italic.family = "JetBrainsMono Nerd Font Mono"
size = 16
offset.y = 2
offset.x = 0

[colors]
primary.background = "#000000"
